language: haskell
ghc: 7.6
install:
    - gem install sass
    - npm install -g coffee-script
script:
    - cabal sandbox init
    - cabal install ./herringbone ./herringbone-wai ./herringbone-embed
    - cd herringbone-tests
    - cabal sandbox init --sandbox ../.cabal-sandbox
    - cabal run herringbone-tests
