language: haskell
ghc: 7.6
install:
    - gem install sass
    - npm install -g coffee-script
script:
    - cabal sandbox init
    - cabal install ./herringbone ./herringbone-wai ./herringbone-embed ./herringbone-tests
    - cd herringbone-tests
    - cabal install --only-dependencies
    - cabal run
